//
//  Country+ISOCode.swift
//  XoomApplication
//
//  Created by John Manos on 4/17/17.
//  Copyright © 2017 John Manos. All rights reserved.
//

/// ISO Country Code
public enum CountryCode: String {
    case Argentina = "AR"
    case Australia = "AU"
    case Austria = "AT"
    case Bangladesh = "BD"
    case Belgium = "BE"
    case Bolivia = "BO"
    case Brazil = "BR"
    case Canada = "CA"
    case Chile = "CL"
    case China = "CN"
    case Colombia = "CO"
    case CostaRica = "CR"
    case Cyprus = "CY"
    case DominicanRepublic = "DO"
    case Ecuador = "EC"
    case ElSalvador = "SV"
    case Estonia = "EE"
    case Finland = "FI"
    case France = "FR"
    case Germany = "DE"
    case Greece = "GR"
    case Guatemala = "GT"
    case Guyana = "GY"
    case Haiti = "HT"
    case Honduras = "HN"
    case HongKong = "HK"
    case India = "IN"
    case Ireland = "IE"
    case Italy = "IT"
    case Jamaica = "JM"
    case Japan = "JP"
    case Kenya = "KE"
    case Latvia = "LV"
    case Lithuania = "LT"
    case Luxembourg = "LU"
    case Malta = "MT"
    case Mexico = "MX"
    case Monaco = "MC"
    case Nepal = "NP"
    case Netherlands = "NL"
    case Nicaragua = "NI"
    case Nigeria = "NG"
    case Pakistan = "PK"
    case Peru = "PE"
    case Philippines = "PH"
    case Poland = "PL"
    case Portugal = "PT"
    case SanMarino = "SM"
    case Singapore = "SG"
    case Slovakia = "SK"
    case Slovenia = "SI"
    case SouthAfrica = "ZA"
    case Spain = "ES"
    case SriLanka = "LK"
    case UnitedKingdom = "GB"
    case Uruguay = "UY"
    case Vietnam = "VN"
}
